[tool.ruff]
# Applies to both linter and formatter unless overridden.
line-length = 88
target-version = "py313"

[tool.ruff.lint]
# Rule sets:
# E = pycodestyle errors, F = pyflakes, I = import sorting (isort compat),
# B = flake8-bugbear (bug-prone patterns), UP = pyupgrade (modernize code).
select = ["E", "F", "I", "B", "UP"]
ignore = []

# Example: ignore specific rules per file (optional)
# per-file-ignores = { "tests/**.py" = ["S101"] }

# isort-compatible options for import sorting (optional but useful)
[tool.ruff.lint.isort]
known-first-party = ["vaultlint"]
# force-single-line = false

[tool.ruff.format]
# Ruff's built-in code formatter (Black-like).
# Use `ruff format` locally and `ruff format --check` in CI to enforce.
quote-style = "preserve"          # keep existing single/double quotes
indent-style = "space"            # use spaces for indentation
skip-magic-trailing-comma = false
