name: Python package (3 OS, sequential Python versions)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  linux:
    name: Linux (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # ---- Python 3.9 ----
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies (3.9)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.9)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.9)
        run: pytest

      # ---- Python 3.10 ----
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies (3.10)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.10)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.10)
        run: pytest

      # ---- Python 3.11 ----
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies (3.11)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.11)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.11)
        run: pytest

      # ---- Python 3.12 ----
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies (3.12)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.12)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.12)
        run: pytest

      # ---- Python 3.13 ----
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies (3.13)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.13)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.13)
        run: pytest

  macos:
    name: macOS (macos-latest)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      # ---- Python 3.9 ----
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies (3.9)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.9)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.9)
        run: pytest

      # ---- Python 3.10 ----
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies (3.10)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.10)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.10)
        run: pytest

      # ---- Python 3.11 ----
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies (3.11)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.11)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.11)
        run: pytest

      # ---- Python 3.12 ----
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies (3.12)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.12)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.12)
        run: pytest

      # ---- Python 3.13 ----
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies (3.13)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.13)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.13)
        run: pytest

  windows:
    name: Windows (windows-latest)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5

      # ---- Python 3.9 ----
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies (3.9)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.9)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.9)
        run: pytest

      # ---- Python 3.10 ----
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies (3.10)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.10)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.10)
        run: pytest

      # ---- Python 3.11 ----
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies (3.11)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.11)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.11)
        run: pytest

      # ---- Python 3.12 ----
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies (3.12)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.12)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.12)
        run: pytest

      # ---- Python 3.13 ----
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies (3.13)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
      - name: Lint (3.13)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test (3.13)
        run: pytest
