name: Python Quality Checks

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # Fast quality checks - fail fast if code quality is poor
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install ruff
        run: python -m pip install --upgrade pip ruff

      - name: Lint with Ruff
        run: ruff check .

      - name: Check formatting with Ruff
        run: ruff format --check .

  # Call the test matrix workflow
  call-test-matrix:
    needs: quality-checks
    uses: ./.github/workflows/test-matrix.yml
