name: Python package

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read # Principle of least privilege for GITHUB_TOKEN

concurrency:
  # Cancel previous runs on the same branch to avoid duplicate jobs
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Fast-fail on formatting/lint to stop early if code quality is poor
  quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Check GPL v3 license headers
        run: python scripts/check_gpl_headers.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip ruff pytest pytest-cov
          python -m pip install -e .

      - name: Lint with Ruff
        run: ruff check .

      - name: Check formatting with Ruff
        run: ruff format --check .

      - name: Check 100% test coverage
        env:
          PACKAGE_NAME: vaultlint
        run: |
          pytest --cov=$PACKAGE_NAME --cov-report=term --cov-fail-under=100
          echo "✅ 100% code coverage achieved"

      - name: CI summary
        if: success()
        run: echo "### Formatting and lint checks passed ✅" >> "$GITHUB_STEP_SUMMARY"

  # Full test matrix - only runs if quality checks pass
  test-matrix:
    needs: quality-checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -e .

      - name: Test with pytest
        run: pytest

  # Single required check for branch protection - aggregates all job results
  check-aggregator:
    name: Check Aggregator
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [quality-checks, test-matrix]
    if: always() # Run even if some jobs fail
    steps:
      - name: Check all job statuses
        run: |
          echo "Checking status of all jobs..."
          echo "Job statuses:"
          echo "  quality-checks: ${{ needs.quality-checks.result }}"
          echo "  test-matrix: ${{ needs.test-matrix.result }}"

          # Check each job explicitly
          if [ "${{ needs.quality-checks.result }}" != "success" ]; then
            echo "❌ Quality checks failed"
            exit 1
          fi

          if [ "${{ needs.test-matrix.result }}" != "success" ]; then
            echo "❌ Test matrix failed"
            exit 1
          fi

          echo "✅ All jobs passed successfully"

      - name: Report success
        if: success()
        run: |
          echo "🎉 All checks passed! Ready to merge."
